### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by VVWVV**
- Fix MAX_PLAYER_NAME
- Add reserve natives
- Fix OnGameModeInit/OnFilterScriptInit, OnGameModeExit/OnFilterScriptExit hooks.
- Optimize code.

### CODE REVIEW

**Comment by Agneese-Saini** [comment]
```pawn
// Mine
if(! (len > 0 && len < 17))

//Yours
if(0 == _:(len > 0 && len < 17))
```
Is actually the same.

```pawn
//Mine
count = strfind(ip, ".", false, 0) + 1;

//Yours
static const symbol[] = !".";
count = strfind(ip, symbol, false, 0) + 1;
```
Why would you create an extra variable to store just a static delimiter???

```pawn
//Mine
GetPlayerName(playerid, _name, MAX_PLAYER_NAME);

//Yours
GetPlayerName(playerid, _name, sizeof (_name));
```
Doesn't really makes a difference!

```pawn
//Mine
new _name[MAX_PLAYER_NAME];

//Yours
new _name[MAX_PLAYER_NAME + 1];
```
Do you know C works on whole numbers ???

I guess you have just fucked up the hooks here or just enlarged the code size: https://github.com/Agneese-Saini/SAMP-ban.inc/pull/1/commits/64fc0f6890afea7015bef651ad6a63c38e6cb272

**Comment by VVWVV** [comment]
This:
````PAWN
if(0 == _:(len > 0 && len < 17))
````
This:
````PAWN
new _name[MAX_PLAYER_NAME + 1];
````

This:
````PAWN
static const symbol[] = !".";
count = strfind(ip, symbol, false, 0) + 1;
````

And This:
````PAWN
GetPlayerName(playerid, _name, sizeof (_name));
````
For optimize...

**Comment by VVWVV** [comment]
I added new file - .gitattributes.

**Comment by Agneese-Saini** [comment]
For optimize... And for normally working.

See assembly listing.

-----
That's not optimization, it's a different way of writing code and that's it, according to me it's a bad coding practice.

**Comment by VVWVV** [comment]
Ok, I'll prove it.

**Comment by VVWVV** [comment]
*
>````PAWN
>main()
>{
>	if(0 == _:(len > 0 && len < 17))
>	{}
>}
>````
>In ASM:
>````Assembly
>CODE 0	; 8
>	proc	; main
>	; line b
>	break	; c
>	; line c
>	break	; 10
>	load.pri 0
>	move.alt
>	zero.pri
>	xchg
>	jsleq 1
>	load.pri 0
>	const.alt 11
>	jsgeq 1
>	const.pri 1
>	jump 2
>l.1
>	zero.pri
>l.2
>	jnz 0
>	;$exp
>l.0		; 64
>	zero.pri
>	retn
>````

>````PAWN
>if(!(len > 0 && len < 17))
>{}
>````
>
>In ASM:
>````Assembly
>CODE 0	; 8
>	proc	; main
>	; line b
>	break	; c
>	; line c
>	break	; 10
>	load.pri 0
>	move.alt
>	zero.pri
>	xchg
>	jsleq 1
>	load.pri 0
>	const.alt 11
>	jsgeq 1
>	const.pri 1
>	jump 2
>l.1
>	zero.pri
>l.2
>	not     ; added stupid asm command
>	jzer 0
>	;$exp
>l.0		; 68
>	zero.pri
>	retn
>````

----

You create the array for the tag and nickname, but you haven't the cell for the zero symbol.

----

````PAWN
static const symbol[] = !".";
count = strfind(ip, symbol, false, 0) + 1;
````
For each new feature creates a new cell in the data segment.

````PAWN
main()
{
	new a= strfind(!"nam", ".", false, 0);
	new b= strfind(!"nam", ".", false, 0);
	new c= strfind(!"nam", ".", false, 0);
}
````
You fill in the data segment is unnecessary symbols.

````Assembly
	proc	; main
	; line b
	break	; c
	; line c
	break	; 10
	;$lcl a fffffffc
	stack fffffffc
	push.c 0
	;$par
	push.c 0
	;$par
	push.c 4
	;$par
	push.c 0
	;$par
	push.c 10
	sysreq.c 0	; strfind
	stack 14
	stor.s.pri fffffffc
	;$exp
	; line d
	break	; 5c
	;$lcl b fffffff8
	stack fffffffc
	push.c 0
	;$par
	push.c 0
	;$par
	push.c 10
	;$par
	push.c c
	;$par
	push.c 10
	sysreq.c 0	; strfind
	stack 14
	stor.s.pri fffffff8
	;$exp
	; line e
	break	; a8
	;$lcl c fffffff4
	stack fffffffc
	push.c 0
	;$par
	push.c 0
	;$par
	push.c 1c
	;$par
	push.c 18
	;$par
	push.c 10
	sysreq.c 0	; strfind
	stack 14
	stor.s.pri fffffff4
	;$exp
	stack c
	zero.pri
	retn


DATA 0	; 0
dump 6e616d00 2e 0 6e616d00 2e 0 6e616d00 2e 0 ; 2e - "."; 6e616d00 - !"nam"
````

**Comment by VVWVV** [comment]
What do you say now?

**Comment by Agneese-Saini** [comment]
Well still the same, it's not called optimization but just a different way of doing it, actually the strfind of yours is just wrong because locating extra memory just for a static symbol is meaningless. If you speed test this, i am always 10% faster than you.

And the first one, yes yours make more sense, it's because i haven't took a look at it since i published that function in "Useful Functions" sticky.

**Comment by VVWVV** [comment]
Ok.

**Pull request closed without merging**
